apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ss-tt-erer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestqa/test:0db58b0a0618d0d53379a5c7592c81b9df75ef20@sha256:61186f5fc537ad49198c19fe409e9ad729661ded1e15858eec44b505918b45b5
          name: container-image
