apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ss-tt-erer
  janus-idp.io/tekton: ss-tt-erer
  backstage.io/kubernetes-id: ss-tt-erer
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ss-tt-erer
resources:
- deployment.yaml
- route.yaml
- service.yaml
