apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ss-tt-erer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ss-tt-erer 
  name: ss-tt-erer
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ss-tt-erer
    weight: 100 
