apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ss-tt-erer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ss-tt-erer 
  name: ss-tt-erer
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ss-tt-erer 
